version: '3.4'

services:
  dockerapidemo:
    image: ${DOCKER_REGISTRY-}dockerapidemo
    build:
      context: .
      dockerfile: DockerApiDemo/Dockerfile
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Testing123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"