// <auto-generated />
using DockerApiDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DockerApiDemo.Data.Migrations
{
    [DbContext(typeof(DockerApiDemoContext))]
    partial class DockerApiDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DockerApiDemo.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "m.verstappen@redbull.com",
                            FirstName = "Max",
                            LastName = "Verstappen",
                            Password = "No1R4cer"
                        },
                        new
                        {
                            Id = 2,
                            Email = "d.ricciardo@renault.com",
                            FirstName = "Daniel",
                            LastName = "Ricciardo",
                            Password = "b1gSM1L35"
                        },
                        new
                        {
                            Id = 3,
                            Email = "k.raikkonen@alfaromeo.com",
                            FirstName = "Kimi",
                            LastName = "Raikkonen",
                            Password = "1W4SHaving4!*&$"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
